fix slack test notification

diff --git a/.github/workflows/test-issue2md.yml b/.github/workflows/test-issue2md.yml
--- a/.github/workflows/test-issue2md.yml
+++ b/.github/workflows/test-issue2md.yml
@@ -25,27 +25,8 @@ jobs:
           issue-url: ${{ github.event.issue.html_url }}
           export-dir: ./issues
           debug: true
-      - name: Check diff
-        id: diff
-        run: |
-          set -x
-          git add -N .
-          # it gets exit code 0 when no diff found
-          git diff --name-only --exit-code
-        continue-on-error: true
-      - name: Push to main branch if any updates exist
-        if: steps.diff.outcome == 'failure'
-        run: |
-          set -e
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git diff
-          git diff-index HEAD
-          git add --all
-          git commit -m "[skip ci] [GitHub Action] Update automatically"
-          git push
       - name: Send custom JSON data to Slack when issue2md failed
-        if: failure() && steps.issue2md.outcome == 'failure'
+        if: failure()
         id: slack
         uses: slackapi/slack-github-action@v1.23.0
         with:
@@ -66,3 +47,22 @@ jobs:
           # currently, it is set to my personal slack channel
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
+      - name: Check diff
+        id: diff
+        run: |
+          set -x
+          git add -N .
+          # it gets exit code 0 when no diff found
+          git diff --name-only --exit-code
+        continue-on-error: true
+      - name: Push to main branch if any updates exist
+        if: steps.diff.outcome == 'failure'
+        run: |
+          set -e
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git diff
+          git diff-index HEAD
+          git add --all
+          git commit -m "[skip ci] [GitHub Action] Update automatically"
+          git push
