[skip ci] fix git diff logic

diff --git a/.github/workflows/test-issue2md.yml b/.github/workflows/test-issue2md.yml
--- a/.github/workflows/test-issue2md.yml
+++ b/.github/workflows/test-issue2md.yml
@@ -28,20 +28,23 @@ jobs:
           issue-url: ${{ github.event.issue.html_url }}
           export-dir: ./issues
           debug: true
-      - name: Push to main branch if any updates exists
+      - name: Check diff
+        id: diff
         run: |
-            set -x
-            gdiff=$(git diff)
-            if [[ -z $gdiff ]]; then
-                echo "No changes"
-            else
-                echo "Update detected"
-                set -e
-                git config --local user.email "action@github.com"
-                git config --local user.name "GitHub Action"
-                git diff
-                git diff-index HEAD
-                git add --all
-                git commit -m "[skip ci] [GitHub Action] Update automatically"
-                git push
-            fi
+          set -x
+          git add -N .
+          # it gets exit code 0 when no diff found
+          git diff --name-only --exit-code
+        continue-on-error: true
+      - name: Push to main branch if any updates exist
+        if: steps.diff.outcome == 'failure'
+        run: |
+            set -e
+            git config --local user.email "action@github.com"
+            git config --local user.name "GitHub Action"
+            git diff
+            git diff-index HEAD
+            git add --all
+            git commit -m "[skip ci] [GitHub Action] Update automatically"
+            git push
+
diff --git a/docs/issue2md.yml b/docs/issue2md.yml
--- a/docs/issue2md.yml
+++ b/docs/issue2md.yml
@@ -13,23 +13,26 @@ jobs:
       - name: Convert issue to markdown
         uses: go-zen-chu/issue2md@main
         with:
-          github-token: ${{ github.token }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
           issue-url: ${{ github.event.issue.html_url }}
           # By default, this action stores markdown to repository root. If you want to change export dir, make directory and change setting below.
           #export-dir: ./issues
-      - name: Push to main branch if any updates exists
+      - name: Check diff
+        id: diff
         run: |
-            gdiff=$(git diff)
-            if [[ -z $gdiff ]]; then
-                echo "No changes"
-            else
-                echo "Update detected"
-                set -e
-                git config --local user.email "action@github.com"
-                git config --local user.name "GitHub Action"
-                git diff
-                git diff-index HEAD
-                git add --all
-                git commit -m "[skip ci] [GitHub Action] Update automatically"
-                git push
-            fi
+          git add -N .
+          # it gets exit code 0 when no diff found
+          git diff --name-only --exit-code
+        continue-on-error: true
+      - name: Push to main branch if any updates exist
+        if: steps.diff.outcome == 'failure'
+        run: |
+            set -e
+            git config --local user.email "action@github.com"
+            git config --local user.name "GitHub Action"
+            git diff
+            git diff-index HEAD
+            git add --all
+            git commit -m "[skip ci] [GitHub Action] Update automatically"
+            git push
+
